// This file is automatically generated. Do not edit it directly.
// Config resolution and degraded-mode fallback are hand-maintained on top of
// the generated client factory.
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function getSupabaseConfig(): { url: string; key: string } | null {
  const url =
    import.meta.env["VITE_SUPABASE_URL"] ||
    (typeof process !== "undefined" ? process.env["SUPABASE_URL"] : undefined);
  const key =
    import.meta.env["VITE_SUPABASE_PUBLISHABLE_KEY"] ||
    (typeof process !== "undefined" ? process.env["SUPABASE_PUBLISHABLE_KEY"] : undefined);

  if (!url || !key) return null;
  return { url, key };
}

function createUnconfiguredSupabaseClient(): SupabaseClient<Database> {
  const error = new Error(
    "Supabase is not configured. Set SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY environment variables.",
  );

  const query: Record<string, unknown> = {
    then: (resolve: (value: { data: null; error: Error }) => void) =>
      resolve({ data: null, error }),
  };
  for (const method of [
    "select",
    "eq",
    "neq",
    "like",
    "ilike",
    "in",
    "or",
    "order",
    "limit",
    "single",
    "maybeSingle",
    "insert",
    "update",
    "delete",
    "upsert",
    "match",
    "textSearch",
  ]) {
    query[method] = () => query;
  }

  return {
    auth: {
      onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }),
      getSession: async () => ({ data: { session: null }, error: null }),
      getUser: async () => ({ data: { user: null }, error }),
      getClaims: async () => ({ data: { claims: null }, error }),
      signInWithPassword: async () => ({ data: null, error }),
      signUp: async () => ({ data: null, error }),
      signInWithOAuth: async () => ({ data: null, error }),
      resetPasswordForEmail: async () => ({ data: null, error }),
      updateUser: async () => ({ data: null, error }),
      signOut: async () => ({ error: null }),
    },
    from: () => query,
  } as unknown as SupabaseClient<Database>;
}

function createSupabaseClient(): SupabaseClient<Database> {
  const config = getSupabaseConfig();

  if (!config) {
    console.warn(
      "[Supabase] Missing SUPABASE_URL / SUPABASE_PUBLISHABLE_KEY. Running in degraded mode.",
    );
    return createUnconfiguredSupabaseClient();
  }

  return createClient<Database>(config.url, config.key, {
    global: {
      fetch: createSupabaseFetch(config.key),
    },
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
